# Generated by Django 4.2.5 on 2023-10-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='date_oub',
            new_name='date_pub',
        ),
    ]
